import Head from 'next/head'
import Link from 'next/link'
import Header from '../components/header'
import Footer from '../components/footer'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header className="md:hidden" color="text-white" />
      <section className="w-full h-screen bg-center bg-cover bg-hero overflow-hidden">
        <div className="text-white font-light font-europa flex flex-col items-end justify-center h-full max-w-[90%] my-auto mx-auto py-8">
          <div className="h-full flex flex-col justify-center text-end">
            <div className="text-4xl"> Maarika Kauksi </div>
            <div className="text-lg tracking-widest mt-2">Photography</div>
            <div className="md:flex tracking-widest mt-7 space-x-3 text-sm hidden">
              <Link href="/portfolio">
                <a>Portfolio</a>
              </Link>
              <Link href="/minust">
                <a>Minust</a>
              </Link>
              <Link href="/">
                <a>Kontakt</a>
              </Link>
              <Link href="/">
                <a>Blog</a>
              </Link>
              <Link href="/">
                <a>Hinnakiri</a>
              </Link>
            </div>
            </div>
        </div>
        <div className="fixed bottom-4 z-20 px-6 w-full">
          <Footer hidden="hidden" className="justify-end" />
        </div>
      </section>
    </div>
  )
}
